# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alert_notification.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'alert_notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61lert_notification.proto\"\xba\x01\n\x11\x41lertNotification\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0c\n\x04\x66\x65\x65\x64\x18\x03 \x01(\t\x12\x10\n\x08\x61udio_id\x18\x04 \x01(\t\x12\x17\n\x0fstart_timestamp\x18\x05 \x01(\t\x12\x15\n\rend_timestamp\x18\x06 \x01(\t\x12\x12\n\ntranscript\x18\x07 \x01(\t\x12\x1c\n\x14\x65valuation_decisions\x18\x08 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alert_notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTNOTIFICATION']._serialized_start=29
  _globals['_ALERTNOTIFICATION']._serialized_end=215
# @@protoc_insertion_point(module_scope)
