# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\"#\n\nAudioChunk\x12\x15\n\rgcs_file_path\x18\x01 \x01(\t\"\xa3\x01\n\x0bSadMetadata\x12\x17\n\x0fsource_chunk_id\x18\x01 \x01(\t\x12,\n\x0cprocessed_at\x18\x02 \x01(\x0b\x32\x16.SadMetadata.Timestamp\x12 \n\x08segments\x18\x03 \x03(\x0b\x32\x0e.SpeechSegment\x1a+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"3\n\rSpeechSegment\x12\x11\n\tstart_sec\x18\x01 \x01(\x02\x12\x0f\n\x07\x65nd_sec\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=15
  _globals['_AUDIOCHUNK']._serialized_end=50
  _globals['_SADMETADATA']._serialized_start=53
  _globals['_SADMETADATA']._serialized_end=216
  _globals['_SADMETADATA_TIMESTAMP']._serialized_start=173
  _globals['_SADMETADATA_TIMESTAMP']._serialized_end=216
  _globals['_SPEECHSEGMENT']._serialized_start=218
  _globals['_SPEECHSEGMENT']._serialized_end=269
# @@protoc_insertion_point(module_scope)
