# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evaluated_transcribed_audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'evaluated_transcribed_audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!evaluated_transcribed_audio.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd1\x07\n\x19\x45valuatedTranscribedAudio\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12\x12\n\nsegment_id\x18\x12 \x01(\t\x12\x12\n\ntranscript\x18\x03 \x01(\t\x12\x33\n\x0fstart_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1d\n\x15missing_prior_context\x18\x06 \x01(\x08\x12\x1c\n\x14missing_post_context\x18\x07 \x01(\x08\x12\x19\n\x11source_audio_uris\x18\x08 \x03(\t\x12\x35\n\x12start_audio_offset\x18\t \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x33\n\x10\x65nd_audio_offset\x18\n \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x1b\n\x13\x63\x61nonical_audio_uri\x18\x0b \x01(\t\x12\x1a\n\x12playback_audio_uri\x18\x0c \x01(\t\x12\x1c\n\x14\x65valuation_decisions\x18\r \x03(\t\x12\x0e\n\x06\x65rrors\x18\x11 \x03(\t\x12\x11\n\tfeed_name\x18\x0f \x01(\t\x12I\n\x10rule_annotations\x18\x13 \x03(\x0b\x32/.EvaluatedTranscribedAudio.RuleAnnotationsEntry\x1a\x41\n\rTextMatchSpan\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x12\x14\n\x0cmatched_text\x18\x03 \x01(\t\x1aN\n\x13TextMatchAnnotation\x12\x37\n\x05spans\x18\x01 \x03(\x0b\x32(.EvaluatedTranscribedAudio.TextMatchSpan\x1a\x64\n\x0eRuleAnnotation\x12\x44\n\ntext_match\x18\x01 \x01(\x0b\x32..EvaluatedTranscribedAudio.TextMatchAnnotationH\x00\x42\x0c\n\nannotation\x1a\x61\n\x14RuleAnnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x38\n\x05value\x18\x02 \x01(\x0b\x32).EvaluatedTranscribedAudio.RuleAnnotation:\x02\x38\x01J\x04\x08\x02\x10\x03J\x04\x08\x0e\x10\x0fJ\x04\x08\x10\x10\x11R\x0ftransmission_idR\x0b\x65xternal_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evaluated_transcribed_audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_RULEANNOTATIONSENTRY']._loaded_options = None
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_RULEANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_EVALUATEDTRANSCRIBEDAUDIO']._serialized_start=103
  _globals['_EVALUATEDTRANSCRIBEDAUDIO']._serialized_end=1080
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_TEXTMATCHSPAN']._serialized_start=686
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_TEXTMATCHSPAN']._serialized_end=751
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_TEXTMATCHANNOTATION']._serialized_start=753
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_TEXTMATCHANNOTATION']._serialized_end=831
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_RULEANNOTATION']._serialized_start=833
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_RULEANNOTATION']._serialized_end=933
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_RULEANNOTATIONSENTRY']._serialized_start=935
  _globals['_EVALUATEDTRANSCRIBEDAUDIO_RULEANNOTATIONSENTRY']._serialized_end=1032
# @@protoc_insertion_point(module_scope)
