# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raw_audio_chunk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raw_audio_chunk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15raw_audio_chunk.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n\nAudioChunk\x12\x0f\n\x07gcs_uri\x18\x01 \x01(\t\x12\x33\n\x0fstart_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\nsession_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\x05\x12\x11\n\tfeed_name\x18\x05 \x01(\t\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x07 \x01(\t\x12&\n\x19\x65xternal_audio_segment_id\x18\t \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_session_idB\x1c\n\x1a_external_audio_segment_idJ\x04\x08\x06\x10\x07J\x04\x08\x08\x10\tR\x0b\x65xternal_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raw_audio_chunk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=59
  _globals['_AUDIOCHUNK']._serialized_end=333
# @@protoc_insertion_point(module_scope)
