# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: segmented_audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'segmented_audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15segmented_audio.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xa7\x05\n\x0eSegmentedAudio\x12\x12\n\nsegment_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x02 \x01(\t\x12\x33\n\x0fstart_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1d\n\x15missing_prior_context\x18\x05 \x01(\x08\x12\x1c\n\x14missing_post_context\x18\x06 \x01(\x08\x12\x19\n\x11source_audio_uris\x18\x07 \x03(\t\x12\x35\n\x12start_audio_offset\x18\x08 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x33\n\x10\x65nd_audio_offset\x18\t \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x11\n\tfeed_name\x18\n \x01(\t\x12\x13\n\x0b\x65xternal_id\x18\x0b \x01(\t\x12\x41\n\x14\x61udio_classification\x18\x0c \x01(\x0e\x32#.SegmentedAudio.AudioClassification\x12\x15\n\rraw_audio_uri\x18\r \x01(\t\x12&\n\x19\x65xternal_audio_segment_id\x18\x0e \x01(\tH\x00\x88\x01\x01\"|\n\x13\x41udioClassification\x12$\n AUDIO_CLASSIFICATION_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x41UDIO_CLASSIFICATION_SPEECH\x10\x01\x12\x1e\n\x1a\x41UDIO_CLASSIFICATION_OTHER\x10\x02\x42\x1c\n\x1a_external_audio_segment_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'segmented_audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEGMENTEDAUDIO']._serialized_start=91
  _globals['_SEGMENTEDAUDIO']._serialized_end=770
  _globals['_SEGMENTEDAUDIO_AUDIOCLASSIFICATION']._serialized_start=616
  _globals['_SEGMENTEDAUDIO_AUDIOCLASSIFICATION']._serialized_end=740
# @@protoc_insertion_point(module_scope)
