# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: streaming_state.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    List,
    Optional,
)

import betterproto


class FlushRequestProtoAudioClassification(betterproto.Enum):
    AUDIO_CLASSIFICATION_UNSPECIFIED = 0
    AUDIO_CLASSIFICATION_SPEECH = 1
    AUDIO_CLASSIFICATION_NO_SPEECH = 2


@dataclass(eq=False, repr=False)
class TimeRangeProto(betterproto.Message):
    """Nested domain dependencies"""

    start_ms: int = betterproto.int64_field(1)
    end_ms: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class FeedMetadataProto(betterproto.Message):
    feed_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class BufferedChunkProto(betterproto.Message):
    timestamp_ms: int = betterproto.int64_field(1)
    gcs_uri: str = betterproto.string_field(2)
    traceparent: Optional[str] = betterproto.string_field(
        3, optional=True, group="_traceparent"
    )


@dataclass(eq=False, repr=False)
class ChunkMetadataProto(betterproto.Message):
    """PCollection Elements (Cross-Worker Boundaries)"""

    gcs_uri: str = betterproto.string_field(1)
    session_id: str = betterproto.string_field(2)
    duration_ms: int = betterproto.int64_field(3)
    feed_metadata: "FeedMetadataProto" = betterproto.message_field(4)
    traceparent: Optional[str] = betterproto.string_field(
        5, optional=True, group="_traceparent"
    )
    is_continuous: bool = betterproto.bool_field(6)
    timestamp_ms: Optional[int] = betterproto.int64_field(
        7, optional=True, group="_timestamp_ms"
    )
    """
    True recording event timestamp of the incoming audio chunk in milliseconds
    since epoch.
    """


@dataclass(eq=False, repr=False)
class FlushRequestProto(betterproto.Message):
    buffer: bytes = betterproto.bytes_field(1)
    feed_id: str = betterproto.string_field(2)
    session_id: str = betterproto.string_field(3)
    contributing_audio_uris: List[str] = betterproto.string_field(4)
    time_range: "TimeRangeProto" = betterproto.message_field(5)
    feed_metadata: "FeedMetadataProto" = betterproto.message_field(7)
    sample_rate: int = betterproto.int32_field(8)
    missing_prior_context: bool = betterproto.bool_field(9)
    missing_post_context: bool = betterproto.bool_field(10)
    start_audio_offset_ms: Optional[int] = betterproto.int64_field(
        11, optional=True, group="_start_audio_offset_ms"
    )
    end_audio_offset_ms: Optional[int] = betterproto.int64_field(
        12, optional=True, group="_end_audio_offset_ms"
    )
    speech_segments: List["TimeRangeProto"] = betterproto.message_field(13)
    traceparent: Optional[str] = betterproto.string_field(
        14, optional=True, group="_traceparent"
    )
    audio_classification: "FlushRequestProtoAudioClassification" = (
        betterproto.enum_field(15)
    )
    segment_id: str = betterproto.string_field(16)


@dataclass(eq=False, repr=False)
class IdleFeedStateProto(betterproto.Message):
    """Persistent State Checkpoints"""

    out_of_order_buffer: List["BufferedChunkProto"] = betterproto.message_field(1)
    order_timer_active: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class ActiveStitchingStateProto(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    feed_metadata: "FeedMetadataProto" = betterproto.message_field(2)
    last_end_time_ms: Optional[int] = betterproto.int64_field(
        3, optional=True, group="_last_end_time_ms"
    )
    stale_start_time_ms: Optional[int] = betterproto.int64_field(
        4, optional=True, group="_stale_start_time_ms"
    )
    buffer_start_time_ms: Optional[int] = betterproto.int64_field(
        5, optional=True, group="_buffer_start_time_ms"
    )
    expected_next_chunk_start_ms: Optional[int] = betterproto.int64_field(
        6, optional=True, group="_expected_next_chunk_start_ms"
    )
    start_audio_offset_ms: Optional[int] = betterproto.int64_field(
        7, optional=True, group="_start_audio_offset_ms"
    )
    end_audio_offset_ms: Optional[int] = betterproto.int64_field(
        8, optional=True, group="_end_audio_offset_ms"
    )
    contributing_audio_uris: List[str] = betterproto.string_field(9)
    missing_prior_context: bool = betterproto.bool_field(10)
    missing_post_context: bool = betterproto.bool_field(11)
    buffer_duration_ms: int = betterproto.int64_field(12)
    order_timer_active: bool = betterproto.bool_field(13)
    out_of_order_buffer: List["BufferedChunkProto"] = betterproto.message_field(14)
    last_transmission_start_ms: Optional[int] = betterproto.int64_field(
        15, optional=True, group="_last_transmission_start_ms"
    )
    speech_segments: List["TimeRangeProto"] = betterproto.message_field(16)
    prior_audio_tail: Optional[bytes] = betterproto.bytes_field(
        17, optional=True, group="_prior_audio_tail"
    )
    traceparent: Optional[str] = betterproto.string_field(
        18, optional=True, group="_traceparent"
    )
    sample_rate: Optional[int] = betterproto.int32_field(
        19, optional=True, group="_sample_rate"
    )


@dataclass(eq=False, repr=False)
class TransmissionContextProto(betterproto.Message):
    idle_state: "IdleFeedStateProto" = betterproto.message_field(1, group="context")
    active_state: "ActiveStitchingStateProto" = betterproto.message_field(
        2, group="context"
    )
