# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcribed_audio.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'transcribed_audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17transcribed_audio.proto\"\x82\x02\n\x10TranscribedAudio\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0c\n\x04\x66\x65\x65\x64\x18\x03 \x01(\t\x12\x10\n\x08\x61udio_id\x18\x04 \x01(\t\x12\x34\n\x0fstart_timestamp\x18\x05 \x01(\x0b\x32\x1b.TranscribedAudio.Timestamp\x12\x32\n\rend_timestamp\x18\x06 \x01(\x0b\x32\x1b.TranscribedAudio.Timestamp\x12\x12\n\ntranscript\x18\x07 \x01(\t\x1a+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribed_audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEDAUDIO']._serialized_start=28
  _globals['_TRANSCRIBEDAUDIO']._serialized_end=286
  _globals['_TRANSCRIBEDAUDIO_TIMESTAMP']._serialized_start=243
  _globals['_TRANSCRIBEDAUDIO_TIMESTAMP']._serialized_end=286
# @@protoc_insertion_point(module_scope)
