repos:
  - repo: local
    hooks:
      - id: generate-protos
        name: generate protobufs
        entry: mise run generate:protos
        language: system
        files: ^protos/.*\.proto$
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ty-check
        name: ty type checker
        entry: uv run ty check
        language: system
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: lint-notebooks
        name: lint notebooks
        entry: mise run lint:notebooks
        language: system
        files: ^model/colabs/.*\.ipynb$
        pass_filenames: false
      - id: proxy-eslint
        name: Run ESLint
        entry: yarn --cwd frontend/api lint:check
        language: system
        files: ^frontend/api/
        pass_filenames: false
      - id: proxy-prettier
        name: Run Prettier
        entry: yarn --cwd frontend/api format:check
        language: system
        files: ^frontend/api/
        pass_filenames: false
      - id: proxy-generate-routes
        name: Generate routes
        entry: yarn --cwd frontend/api generate-routes
        language: system
        files: ^frontend/api/
        pass_filenames: false
      - id: proxy-type-check
        name: Type check
        entry: yarn --cwd frontend/api run tsc --noEmit
        language: system
        files: ^frontend/api/
        pass_filenames: false
      - id: verify-openapi-spec
        name: Verify OpenAPI Spec
        entry: yarn --cwd frontend/api verify-spec
        language: system
        files: ^frontend/api/
        pass_filenames: false
      - id: ui-eslint
        name: Run ESLint
        entry: yarn --cwd frontend/transcription-ui lint:check
        language: system
        files: ^frontend/transcription-ui/
        pass_filenames: false
      - id: ui-prettier
        name: Run Prettier
        entry: yarn --cwd frontend/transcription-ui format:check
        language: system
        files: ^frontend/transcription-ui/
        pass_filenames: false
      - id: ui-type-check
        name: Type check
        entry: yarn --cwd frontend/transcription-ui run tsc --noEmit
        language: system
        files: ^frontend/transcription-ui/
        pass_filenames: false
