services:
  # NeMo CLI container for running NeMo on CPU - CPU version
  nemo-cli-cpu: &nemo-cli-base
    build:
      context: .
      dockerfile: model/nemo_docker/Dockerfile
    network_mode: "host"
    volumes:
      - ./model:/app
      # This maps the cloud credentials on your local machine onto the docker container.
      - ${HOME}/.config/gcloud:/root/.config/gcloud
    working_dir: /workspace/nemo
    environment:
      - JUPYTER_PATH=/opt/venv/share/jupyter
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    entrypoint: ["/bin/zsh"]

  # NeMo CLI container with GPU support
  nemo-cli-gpu:
    <<: *nemo-cli-base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Lightweight ASR experiment runtime (without NeMO) - CPU version
  notebooks-cpu: &notebooks-base
    build:
      context: ./model
      dockerfile: notebook_docker/Dockerfile
    network_mode: "host"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
    volumes:
      - .:/workspace
      # This maps the cloud credentials on your local machine onto the docker container.
      - ${HOME}/.config/gcloud:/root/.config/gcloud
    working_dir: /workspace
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json

  # Lightweight ASR experiment runtime with GPU support
  notebooks:
    <<: *notebooks-base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.password=''"]
    working_dir: /workspace
    volumes:
      - .:/workspace
