services:
  frontend-api:
    build:
      context: .
      dockerfile: frontend/api/Dockerfile
    ports:
      - "127.0.0.1:8088:8080"
    env_file:
      - path: ./local_dev/LOCAL.env
      - path: .env
        required: false
    environment:
      - TRANSCRIPTS_API_URL=http://transcripts-api:8087/v1/transcripts
      - AUDIO_SEGMENTS_API_URL=http://audio-segments-api:8091/v1/audio_segments
      - FEEDS_STORE_API_URL=http://feeds-api:8089/v1/feeds
      - RULES_API_URL=http://rules-management:8086/v1/rules
    networks:
      - pipeline-network
    depends_on:
      - transcripts-api
      - rules-management
      - audio-segments-api

networks:
  pipeline-network:
