syntax = "proto3";

message NormalizedAudio {
  message Timestamp {
    int64 seconds = 1;
    int32 nanos = 2;
  }
  message Duration {
    int64 seconds = 1;
    int32 nanos = 2;
  }

  reserved 1;
  reserved "transmission_id";

  string feed_id = 2;
  string segment_id = 15;
  Timestamp start_timestamp = 3;
  Timestamp end_timestamp = 4;
  bool missing_prior_context = 5;
  bool missing_post_context = 6;
  repeated string source_audio_uris = 7;
  Duration start_audio_offset = 8;
  Duration end_audio_offset = 9;
  string canonical_audio_uri = 10;
  string playback_audio_uri = 11;
  string feed_name = 12;

  reserved 13;
  reserved "external_id";

  enum AudioClassification {
    AUDIO_CLASSIFICATION_UNSPECIFIED = 0;
    AUDIO_CLASSIFICATION_SPEECH = 1;
    AUDIO_CLASSIFICATION_OTHER = 2;
  }

  AudioClassification audio_classification = 14;
  optional string transcription_audio_uri = 16;
}
