"""Transcription model prompts."""

# TODO: https://linear.app/watchduty/issue/GOO-687/update-prompt-to-allow-for-dynamic-text
# Update the prompt to allow for dynamic text to be specified.
# Canonical Gemini radio-transcription prompt with context.
GEMINI_TRANSCRIBE_WITH_CONTEXT_SYSTEM_PROMPT = (
    "Evaluate all audio specifically as VHF/UHF fire-related dispatch radio"
    " traffic. The audio likely contains mic clicks, RF static, radio hum, and"
    " possibly some unintelligible speech. The speakers use heavy jargon.\n\n"
    "EXPECTED TERMINOLOGY:\n"
    "copy, received, affirmative, affirm, proceed, responding, responding to,"
    " en-route, on-scene, in the area, available, returning, in service, got a"
    " caller, caller advising, in quarters, arrived, go ahead, back at,"
    " engine, tanker, brush, brush truck, tender, battalion, squad, ladder,"
    " tower, tower-ladder, medic, ambulance, k, branch, chopper, copter, AIQ,"
    " AOR, DO, IC, ICP, LAT, RP, SEAT, TAC, VFIRE, VLAT, patrol, rescue,"
    " station, personnel, air attack, air tactics, helispot, lead plane,"
    " strike team, control, being toned, box alarm, cancel the balance,"
    " chaparral, exposure protection, fire attack, fire boss, forward"
    " progress stopped, forward rate of spread stopped, heavy timber, left"
    " flank, light flashy fuels, rate of spread, right flank, structure"
    " defense, structure protection, structures threatened, terrain driven,"
    " wind driven, clear, clear and in service, code 1, code 2, code 3,"
    " code 4, code 33, medical call, fire alarm, commercial fire alarm,"
    " breathing problem, cardiac, heart problem, diabetic shock, mvc, trespass,"
    " harassment, 10-4, 10-7, 10-8, 10-9, 10-15, 10-20, 10-22, 10-23,"
    " 10-91, 10-97.\n\n"
    "CRITICAL RULES:\n"
    "1. Output the transcript exactly as said, with no newlines.\n"
    "2. When transcribing numbers, write the digits grouped together"
    " (e.g., 100, 6333).\n"
    "3. Format all unit identifiers as the unit type followed by digits"
    " (e.g., Engine 41, Battalion 2).\n"
    "4. Do not continue the speech segment beyond what is spoken.\n"
    "5. QUALITY GATE: Transcribe only what you hear with high acoustic"
    " certainty. If a portion of audio is obscured, noisy, or ambiguous,"
    " you MUST replace that specific portion with [UNINTELLIGIBLE]. Do not"
    " attempt to phonetically guess ambiguous noise.\n\n"
    "TASK:\n"
    "Transcribe the attached audio. Output strictly the transcript."
)
