name: 'Post Frontend Coverage'
description: 'Emits frontend test coverage as a Check Run'
inputs:
  name:
    description: 'Name of the tests that the coverage is for'
    required: true
  coverage-report-location:
    description: 'Path to the text coverage report file'
    required: true
  json-summary-location:
    description: 'Path to the JSON coverage summary file'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Coverage Check Run
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          // Use HEAD for pull requests, and all other types of runs (e.g. manual trigger)
          // will use the commit SHA.
          const ref = context.payload.pull_request ? context.payload.pull_request.head.sha : context.sha;
          
          const testName = `${{ inputs.name }}`;
          const reportFile = `${{ inputs.coverage-report-location }}`;
          const jsonSummary = `${{ inputs.json-summary-location }}`;
          
          if (fs.existsSync(jsonSummary)) {
            try {
              const data = JSON.parse(fs.readFileSync(jsonSummary, 'utf8'));
              const coveragePct = `${data.total.statements.pct}%`;
              const pctNumber = parseFloat(data.total.statements.pct);
              let conclusion = 'success';
              if (pctNumber < 50) {
                conclusion = 'failure';
              } else if (pctNumber < 80) {
                conclusion = 'neutral';
              }

              const codeBlock = '```';
              let summary = 'No coverage report found';
              if (fs.existsSync(reportFile)) {
                summary = `### Coverage Report\n\n${codeBlock}\n${fs.readFileSync(reportFile, 'utf8')}\n${codeBlock}`;
              }
              
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head_sha: ref,
                name: `${testName}: ${coveragePct}`,
                status: 'completed',
                conclusion: conclusion,
                output: {
                  title: `${testName}: ${coveragePct}`,
                  summary: summary,
                }
              });

              if (conclusion === 'failure') {
                core.setFailed(`Coverage for ${testName} is ${coveragePct}, which is below the 50% failure threshold.`);
              } else if (conclusion === 'neutral') {
                core.warning(`Coverage for ${testName} is ${coveragePct}, which is below the 80% warning threshold.`);
              }
            } catch (e) {
              core.warning(`Failed to parse json summary for ${testName}: ${e}`);
            }
          } else {
            core.info(`JSON summary file not found at ${jsonSummary}`);
          }
