"""Constants shared across the pipeline and tests."""

DEAD_LETTER_QUEUE_TAG = "transcription_dlq"

# Default path to the packaged Chirp phrase hints file in the container image.
DEFAULT_PHRASE_HINTS_FILE_PATH = (
    "/app/backend/pipeline/transcription/chirp_phrase_hints.txt"
)

# Default path to the packaged Chirp custom prompt file in the container image.
DEFAULT_CHIRP_PROMPT_FILE_PATH = (
    "/app/backend/pipeline/transcription/chirp_prompt.txt"
)

# Marker defined in the prompt to indicate when the model detects no intelligible speech.
CHIRP_UNINTELLIGIBLE_MARKER = "[UNINTELLIGIBLE]"

# Chirp model configuration defaults
DEFAULT_CHIRP_LOCATION = "us"
DEFAULT_CHIRP_RECOGNIZER = "_"
DEFAULT_CHIRP_MODEL = "chirp_3"
DEFAULT_CHIRP_LANGUAGE_CODES = ["en-US"]

# Pipeline Defaults
DEFAULT_SIGNIFICANT_GAP_MS = 800
DEFAULT_STALE_TIMEOUT_MS = 75000
DEFAULT_BYPASS_STALE_TIMEOUT_MS = 5000
DEFAULT_MAX_TRANSMISSION_DURATION_MS = 60000
DEFAULT_CONTINUOUS_OUT_OF_ORDER_TIMEOUT_MS = 60000
DEFAULT_SEGMENTED_OUT_OF_ORDER_TIMEOUT_MS = 10000
DEFAULT_FLOAT_TOLERANCE_MS = 500
MAIN_TAG = "main"

# API Retry Configuration
DEFAULT_MAX_RETRIES = 5
DEFAULT_RETRY_MAX_SECONDS = 10

# Telemetry Metrics
GCP_METRIC_PREFIX = "custom.googleapis.com/radio_transcription"
GCP_DURATION_METRIC_NAME = "transcription_time"
GCP_STITCHING_METRIC_NAME = "stitching_time"


# Audio Filter Parameters
HIGHPASS_FILTER_FREQ = 300
LOWPASS_FILTER_FREQ = 3000

# Voice Activity Detection Defaults
DEFAULT_TENVAD_THRESHOLD = 0.5
DEFAULT_TENVAD_HOP_SIZE = 256
DEFAULT_TENVAD_MIN_SPEECH_MS = 300
DEFAULT_VAD_PRE_ROLL_MS = 1000
DEFAULT_VAD_POST_ROLL_MS = 1000

# Audio Signal Processing Boundaries
INT16_MAX_FLOAT = 32768.0
BYTES_PER_SAMPLE_16BIT = 2

# DSP Mathematical Heuristic Defaults
DEFAULT_SED_FFT_SIZE = 2048
DEFAULT_SED_HOP_SIZE = 512
BACKGROUND_NOISE_PERCENTILE = 10
DYNAMIC_ENERGY_MULTIPLIER = 2.5
MEDIAN_FILTER_VOTING_THRESHOLD = 0.5
VAD_RMS_SILENCE_THRESHOLD = 0.005
VAD_FLATNESS_NOISE_THRESHOLD = 0.6

# Acoustic Gate Detector Defaults
DEFAULT_AGD_THRESHOLD = 0.4
DEFAULT_AGD_LOWER_THRESHOLD = 0.005
DEFAULT_AGD_ENERGY_THRESHOLD = 0.025
DEFAULT_AGD_DEBOUNCE_WINDOW_SEC = 0.2
DEFAULT_AGD_HANGOVER_FRAMES = 3
DEFAULT_AGD_LOW_FREQ_HZ = 300.0
DEFAULT_AGD_HIGH_FREQ_HZ = 3400.0
DEFAULT_AGD_FFT_SIZE = 2048
DEFAULT_AGD_HOP_SIZE = 320
MIN_AGD_FFT_SIZE = 256
