"""Constants shared across the pipeline and tests."""

DEAD_LETTER_QUEUE_TAG = "transcription_dlq"

# Default path to the packaged Chirp phrase hints file in the container image.
DEFAULT_PHRASE_HINTS_FILE_PATH = (
    "/app/backend/pipeline/transcription/chirp_phrase_hints.txt"
)

# Default path to the packaged Chirp custom prompt file in the container image.
DEFAULT_CHIRP_PROMPT_FILE_PATH = (
    "/app/backend/pipeline/transcription/chirp_prompt.txt"
)

# Marker defined in the prompt to indicate when the model detects no intelligible speech.
CHIRP_UNINTELLIGIBLE_MARKER = "[UNINTELLIGIBLE]"

# Chirp model configuration defaults
DEFAULT_CHIRP_LOCATION = "us"
DEFAULT_CHIRP_RECOGNIZER = "_"
DEFAULT_CHIRP_MODEL = "chirp_3"
DEFAULT_CHIRP_LANGUAGE_CODES = ["en-US"]

# Pipeline Defaults
DEFAULT_SIGNIFICANT_GAP_MS = 800
DEFAULT_STALE_TIMEOUT_MS = 75000
DEFAULT_BYPASS_STALE_TIMEOUT_MS = 5000
DEFAULT_MAX_TRANSMISSION_DURATION_MS = 60000
DEFAULT_CONTINUOUS_OUT_OF_ORDER_TIMEOUT_MS = 60000
DEFAULT_SEGMENTED_OUT_OF_ORDER_TIMEOUT_MS = 10000
DEFAULT_FLOAT_TOLERANCE_MS = 500
MAIN_TAG = "main"

# API Retry Configuration
DEFAULT_MAX_RETRIES = 5
DEFAULT_RETRY_MAX_SECONDS = 10


# Audio Filter Parameters
HIGHPASS_FILTER_FREQ = 300
LOWPASS_FILTER_FREQ = 3000

# Voice Activity Detection Defaults
VAD_DEFAULT_HIGHPASS_HZ = 300.0
VAD_DEFAULT_LOWPASS_HZ = 4000.0
VAD_DEFAULT_BLEND_RATIO = 0.9
VAD_DEFAULT_BOOST_FREQ_HZ = 2500.0
VAD_DEFAULT_BOOST_GAIN_DB = 10.0
VAD_DEFAULT_PEAK_FILTER_Q = 1.0
VAD_DEFAULT_THRESHOLD_ONSET = 0.35
VAD_DEFAULT_THRESHOLD_OFFSET = 0.10
VAD_DEFAULT_MIN_SPEECH_DURATION_MS = 100
VAD_DEFAULT_MIN_SILENCE_DURATION_MS = 500
VAD_DEFAULT_PAD_SEC = 0.0
VAD_DEFAULT_PRIMING_SEC = 6.0
DEFAULT_VAD_PRE_ROLL_MS = 300
DEFAULT_VAD_POST_ROLL_MS = 500

# Audio Signal Processing Boundaries
INT16_MAX_FLOAT = 32768.0

# DSP Mathematical Heuristic Defaults
DEFAULT_SED_FFT_SIZE = 2048
DEFAULT_SED_HOP_SIZE = 512
VAD_RMS_SILENCE_THRESHOLD = 0.005
