"""Constants shared across the pipeline and tests."""

DEAD_LETTER_QUEUE_TAG = "transcription_dlq"

# Pipeline Defaults
DEFAULT_SIGNIFICANT_GAP_MS = 1500
DEFAULT_STALE_TIMEOUT_MS = 45000
DEFAULT_MAX_TRANSMISSION_DURATION_MS = 600000
DEFAULT_OUT_OF_ORDER_TIMEOUT_MS = 15000
DEFAULT_FLOAT_TOLERANCE_MS = 500
MAIN_TAG = "main"

# API Retry Configuration
DEFAULT_MAX_RETRIES = 5
DEFAULT_RETRY_MAX_SECONDS = 10

# Telemetry Metrics
GCP_METRIC_PREFIX = "custom.googleapis.com/radio_transcription"
GCP_DURATION_METRIC_NAME = "transcription_time"
GCP_STITCHING_METRIC_NAME = "stitching_time"


# Audio Filter Parameters
HIGHPASS_FILTER_FREQ = 300
LOWPASS_FILTER_FREQ = 3000

# Voice Activity Detection Defaults
DEFAULT_TENVAD_THRESHOLD = 0.5
DEFAULT_TENVAD_HOP_SIZE = 256
DEFAULT_TENVAD_MIN_SPEECH_MS = 100
DEFAULT_VAD_PRE_ROLL_MS = 500
DEFAULT_VAD_POST_ROLL_MS = 500
