"""Stateful Apache Beam DoFns for chronological sequence timeline logic and stitch generation."""

import logging
import time
from collections.abc import Iterator
from datetime import UTC, datetime
from typing import Any, override

import apache_beam as beam
from apache_beam.metrics import Metrics
from apache_beam.transforms.userstate import (
    ReadModifyWriteRuntimeState,
    ReadModifyWriteStateSpec,
)

from backend.pipeline.common.constants import (
    MS_PER_SECOND,
    SAMPLE_RATE_HZ,
)
from backend.pipeline.common.storage.gcs_uploader import GCSAudioUploader
from backend.pipeline.transcription.audio_processor import AudioProcessor
from backend.pipeline.transcription.constants import (
    DEAD_LETTER_QUEUE_TAG,
)
from backend.pipeline.transcription.datatypes import (
    FlushRequest,
    TranscribeAudioConfig,
    TranscriptionResult,
)

# Force Dataflow workers to load TranscriptionOptions so it recognizes custom flags
from backend.pipeline.transcription.options import (
    TranscriptionOptions,  # noqa: F401
)
from backend.pipeline.transcription.resources import (
    SHARED_RESOURCE_HANDLE,
    SharedResources,
)
from backend.pipeline.transcription.transcribers import (
    Transcriber,
    get_transcriber,
)

logger = logging.getLogger(__name__)


SEQUENTIAL_BARRIER_SPEC = ReadModifyWriteStateSpec(
    "sequential_barrier", beam.coders.BooleanCoder()
)
# A dummy state parameter used exclusively to enforce chronological processing constraints on the Beam Runner per feed_id.
SEQUENTIAL_BARRIER_STATE = beam.DoFn.StateParam(SEQUENTIAL_BARRIER_SPEC)


@beam.typehints.with_input_types(tuple[str, FlushRequest])
@beam.typehints.with_output_types(TranscriptionResult)
class TranscribeAudioFn(beam.DoFn):
    """Submits the concatenated FLAC buffers generated by the upstream Stitcher to the
    transcription API and serializes the transcripts into a TranscriptionResult dataclass.
    """

    def __init__(
        self,
        config: TranscribeAudioConfig,
        transcriber_factory: Any | None = None,
    ) -> None:
        """Binds the TranscribeAudioConfig and initializes Beam metrics counters."""
        self.config = config
        self.transcriber_factory = transcriber_factory or get_transcriber

        self.audio_processor: AudioProcessor | None = None
        self.transcriber: Transcriber | None = None

        self.vad_speech_count = Metrics.counter(
            "TranscribeAudioFn", "vad_speech_count"
        )
        self.vad_silence_count = Metrics.counter(
            "TranscribeAudioFn", "vad_silence_count"
        )
        self.transcription_count = Metrics.counter(
            "TranscribeAudioFn", "transcription_count"
        )
        self.dlq_count = Metrics.counter("TranscribeAudioFn", "dlq_count")

        self.speech_duration_sec_dist = Metrics.distribution(
            "TranscribeAudioFn", "speech_duration_sec"
        )
        self.vad_eval_time_ms = Metrics.distribution(
            "TranscribeAudioFn", "vad_eval_time_ms"
        )
        self.transcription_time_ms = Metrics.distribution(
            "TranscribeAudioFn", "transcription_time_ms"
        )

    @override
    def setup(self) -> None:
        """Initializes internal clients once per worker."""
        # Grab the global pool singleton
        self.shared_resources = SHARED_RESOURCE_HANDLE.acquire(SharedResources)

        self.audio_processor = AudioProcessor(
            self.config.vad_type,
            self.config.vad_config,
            shared_resources=self.shared_resources,
        )
        self.audio_processor.setup()

        self.transcriber = self.shared_resources.get_transcriber(
            factory=self.transcriber_factory,
            transcriber_type=self.config.transcriber_type,
            project_id=self.config.project_id,
            config_json=self.config.transcriber_config,
        )

        if self.audio_processor.gcs_client is None:
            msg = "GCS client not found in AudioProcessor. must call setup() first."
            raise RuntimeError(msg)

        self.audio_uploader = GCSAudioUploader(
            gcs_client=self.audio_processor.gcs_client,
        )

    def _export_and_transcribe(
        self,
        request: FlushRequest,
    ) -> TranscriptionResult | None:
        """Concatenates buffered chunks, renders to an intermediate audio format, and dispatches to the inference client."""
        if self.audio_processor is None:
            msg = "AudioProcessor not initialized. setup() must be called."
            raise RuntimeError(msg)
        if self.transcriber is None:
            msg = "Transcriber not initialized. setup() must be called."
            raise RuntimeError(msg)

        if request.buffer is None or request.buffer.size == 0:
            return None

        success, flac_bytes, processed_audio = (
            self.audio_processor.process_buffer(request.buffer)
        )
        if not success or flac_bytes is None or processed_audio is None:
            self.vad_silence_count.inc()
            logger.info(
                "VAD detected no speech in buffer. Dropping transmission."
            )
            return None

        self.vad_speech_count.inc()
        duration_sec = len(processed_audio) / float(SAMPLE_RATE_HZ)
        self.speech_duration_sec_dist.update(int(duration_sec))

        if not self.config.canonical_audio_bucket:
            canonical_audio_uri, playback_audio_uri = None, None
        else:
            dt = datetime.fromtimestamp(
                request.time_range.start_ms / 1000.0, tz=UTC
            )

            flac_path = f"lossless/{request.feed_id}/{dt:%Y/%m/%d}/{request.transmission_id}.flac"
            m4a_path = f"playback/{request.feed_id}/{dt:%Y/%m/%d}/{request.transmission_id}.m4a"

            canonical_audio_uri, playback_audio_uri = (
                self.audio_uploader.upload_audio_derivatives(
                    bucket_name=self.config.canonical_audio_bucket,
                    flac_path=flac_path,
                    m4a_path=m4a_path,
                    flac_bytes=flac_bytes,
                    processed_audio=processed_audio,
                    export_m4a_fn=self.audio_processor.export_m4a,
                )
            )
        if not canonical_audio_uri and (
            request.contributing_audio_uris
            and len(request.contributing_audio_uris) == 1
        ):
            canonical_audio_uri = request.contributing_audio_uris[0]

        transcribe_start = time.time()

        transcript = self.transcriber.transcribe(
            audio_data=flac_bytes,
        )
        if transcript is None:
            logger.info("Transcription yielded no text. Dropping transmission.")
            return None
        duration_ms = int((time.time() - transcribe_start) * MS_PER_SECOND)
        self.transcription_time_ms.update(duration_ms)

        logger.info(f"TRANSCRIPT [{request.feed_id}]: {transcript}")

        if request.start_audio_offset_ms is None:
            msg = "Missing start_audio_offset_ms in FlushRequest"
            raise ValueError(msg)
        if request.end_audio_offset_ms is None:
            msg = "Missing end_audio_offset_ms in FlushRequest"
            raise ValueError(msg)
        if canonical_audio_uri is None:
            msg = "Missing canonical_audio_uri"
            raise ValueError(msg)
        if playback_audio_uri is None:
            msg = "Missing playback_audio_uri"
            raise ValueError(msg)

        return TranscriptionResult(
            feed_id=request.feed_id,
            session_id=request.session_id,
            contributing_audio_uris=request.contributing_audio_uris,
            transcript=transcript,
            time_range=request.time_range,
            transmission_id=request.transmission_id,
            missing_prior_context=request.missing_prior_context,
            missing_post_context=request.missing_post_context,
            start_audio_offset_ms=request.start_audio_offset_ms,
            end_audio_offset_ms=request.end_audio_offset_ms,
            canonical_audio_uri=canonical_audio_uri,
            playback_audio_uri=playback_audio_uri,
        )

    @override
    def process(  # type: ignore[override]
        self,
        element: tuple[str, FlushRequest],
        sequential_barrier: ReadModifyWriteRuntimeState = SEQUENTIAL_BARRIER_STATE,  # type: ignore
        *args: Any,
        **kwargs: Any,
    ) -> Iterator[TranscriptionResult | beam.pvalue.TaggedOutput]:
        """Submits the consolidated flushed buffer strictly sequentially to the external transcription API."""
        feed_id, request = element
        try:
            transcribed = self._export_and_transcribe(request)
            if transcribed:
                self.transcription_count.inc()
                yield transcribed
        except Exception as e:
            if not self.config.route_to_dlq:
                raise
            self.dlq_count.inc()
            logger.exception("Error transcribing buffer for feed %s", feed_id)
            msg = str(e)
            yield beam.pvalue.TaggedOutput(
                DEAD_LETTER_QUEUE_TAG, {"error": msg, "feed_id": feed_id}
            )
