"""Data models and contract for the ingestion pipeline.

Runtime / Capture Contract
==========================

The ``yield`` is the contract boundary. Before yield = capture's
domain. After yield = runtime's domain.

**Runtime owns:** GCS upload, Pub/Sub publish, bookmarks, failure
counting, quarantine, heartbeats, lease release, timeouts.

**Capture owns:** connections, reconnection, retries, rate limits,
data validation, shutdown checks, session_id generation.

The capture function must appear as an infinite async generator.
Transport disconnections are internal — the runtime never sees them.

Error Handling
--------------

For any error inside a capture function:

- **Configuration error** (bad creds, wrong URL): raise immediately.
- **Rate limit** (429): back off internally, never propagate.
- **Transient error** (500, timeout, disconnect): retry internally.
  If a single item is exhausted, skip it. If the connection fails
  persistently, raise to the runtime.
- **Item failure** (one file 404, corrupt data): skip, log, continue.
  If ALL items fail with the same error class, raise (systemic).
- **Data quality** (zero-length, bad timestamp): filter silently.
- **Unknown**: let it propagate naturally.

Session ID
----------

The capture function always generates ``session_id``. The runtime
treats it as opaque — stores but never generates or interprets it.

- **Continuous stream** (Icecast): one UUID per connection.
- **Discrete calls** (OpenMHZ): one UUID per (talkgroup, connection).
- **File-based** (Echo): one UUID per file.

Hard Rules
----------

The capture function must **never**:

1. Write to the database (bookmarks, failure counts, lease release).
2. Catch ``CancelledError`` and suppress it.
3. Use ``asyncio.sleep()`` — use shutdown-interruptible sleep.
4. Block the event loop (no sync I/O).
5. Hold unbounded state.
6. Yield chunks after ``shutdown.is_set()``.
"""

from __future__ import annotations

import dataclasses
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import asyncio
    import datetime
    from collections.abc import AsyncIterator, Callable

    from backend.pipeline.storage.feed_store import LeasedFeed


@dataclasses.dataclass(frozen=True)
class CapturedChunk:
    """A single captured audio chunk yielded by a capture function.

    Attributes:
        audio_bytes: The raw audio file bytes for this segment.
        chunk_start_time: The UTC timestamp of the beginning of the audio window.
        chunk_end_time: The UTC timestamp of the end of the audio window.
        session_id: Opaque session identifier generated by the capture function.
            Groups chunks from a contiguous logical audio stream. The runtime
            stores it but never generates or interprets it. ``None`` triggers a
            fallback UUID in the runtime (transitional — all collectors should
            set this).
    """

    audio_bytes: bytes
    chunk_start_time: datetime.datetime
    chunk_end_time: datetime.datetime
    session_id: str | None = None


if TYPE_CHECKING:
    # 3-arg collector: (feed, shutdown_event, url_base) -> AsyncIterator[CapturedChunk]
    CollectorFn = Callable[
        [LeasedFeed, asyncio.Event, str],
        AsyncIterator[CapturedChunk],
    ]
