"""Data models and contract for the ingestion pipeline.

Runtime / Capture Contract
==========================

The ``yield`` is the contract boundary.

**Runtime owns** (capture must never do these):
GCS upload, Pub/Sub publish, bookmarks, failure counting,
quarantine, heartbeats, lease release, timeouts.

**Capture owns:**
Connections, reconnection, retries, rate limits, data validation,
shutdown checks, session_id generation. The capture function must
appear as an infinite async generator — transport disconnections
are internal events the runtime never sees.

Error Handling
--------------

For any error inside a capture function, follow this priority:

1. **Configuration** (bad creds, wrong URL): raise immediately.
2. **Rate limit** (429): back off internally, never propagate.
3. **Transient** (500, timeout, disconnect): retry internally.
   Skip the item if retries exhaust. Raise if the connection
   fails persistently (e.g. 10 consecutive transport failures).
4. **Item failure** (one download 404, corrupt data): skip, log,
   continue. Raise if ALL items in a batch fail (systemic).
5. **Data quality** (zero-length, bad timestamp): filter silently.
6. **Unknown**: let it propagate — the runtime will record the
   failure and release the lease.

Session ID
----------

The capture function always generates ``session_id``. The runtime
treats it as opaque — stores but never generates or interprets it.

Choose a model based on your source type:

- **Continuous stream** (Icecast): one UUID per connection lifetime.
- **Discrete calls, persistent connection** (OpenMHZ): one UUID
  per (talkgroup, connection). New connection = new session.
- **Discrete calls, polling** (Broadcastify Calls): one UUID per
  collector function call. The function's lifetime = the session.
- **File-based** (Echo): one UUID per file.

Hard Rules
----------

The capture function must **never**:

1. Write to the database.
2. Catch ``CancelledError`` and suppress it (use ``try/finally``).
3. Use ``asyncio.sleep()`` — use shutdown-interruptible sleep.
4. Block the event loop (no sync I/O).
5. Hold unbounded state.
6. Yield chunks after ``shutdown.is_set()``.
"""

from __future__ import annotations

import dataclasses
from typing import TYPE_CHECKING

import aiohttp  # noqa: TC002 — runtime use: CaptureResources holds aiohttp.ClientSession

if TYPE_CHECKING:
    import asyncio
    import datetime
    from collections.abc import AsyncIterator, Callable

    from backend.pipeline.storage.feed_store import LeasedFeed


@dataclasses.dataclass(frozen=True)
class CapturedChunk:
    """A single captured audio chunk yielded by a capture function.

    Attributes:
        audio_bytes: The raw audio file bytes for this segment.
        chunk_start_time: The UTC timestamp of the beginning of the audio window.
        chunk_end_time: The UTC timestamp of the end of the audio window.
        session_id: Opaque session identifier generated by the capture function.
            Groups chunks from a contiguous logical audio stream. The runtime
            stores it but never generates or interprets it. ``None`` triggers a
            fallback UUID in the runtime (transitional — all collectors should
            set this).
        receipt_time: UTC-timezone-aware datetime stamped by the capture function
            at the moment the upstream-source event arrived at the collector
            (segment finalization for Icecast, WS event arrival for OpenMHZ,
            per-call iteration for bcfy_calls). ``None`` propagates silently:
            the downstream latency-emitting log OMITS ``processing_latency_sec``
            entirely from the payload when unset (the key is absent, not null).
            Required to be tz-aware UTC when set.
    """

    audio_bytes: bytes
    chunk_start_time: datetime.datetime
    chunk_end_time: datetime.datetime
    session_id: str | None = None
    receipt_time: datetime.datetime | None = None


@dataclasses.dataclass(frozen=True, kw_only=True)
class CaptureResources:
    """Runtime-owned resources passed to capture functions.

    Constructed once in NormalizerRuntime._main() and lifecycle-managed
    by the runtime: http_session is closed in _shutdown_sequence after
    _gcs_client.close() (followed by a 250ms SSL-teardown sleep, per
    aiohttp's documented graceful-shutdown idiom for SSL).

    Forward-compatible container — additional runtime-owned resources
    (e.g. the deferred ffmpeg spawn semaphore) can be added without
    another signature break.

    Attributes:
        http_session: Shared aiohttp ClientSession with TCPConnector
            tuned for the bcfy_calls polling workload (limit=0,
            limit_per_host=64, ttl_dns_cache=300, keepalive_timeout=75).
            NOT Optional — Phase 3 collectors will assume it's always
            set; constructing real instances from day one keeps ty
            strict.
    """

    http_session: aiohttp.ClientSession


if TYPE_CHECKING:
    # 4-arg collector: (feed, shutdown_event, url_base, resources)
    # -> AsyncIterator[CapturedChunk]
    CollectorFn = Callable[
        [LeasedFeed, asyncio.Event, str, CaptureResources],
        AsyncIterator[CapturedChunk],
    ]
