name: 'Free Disk Space'
description: 'Frees host SSD disk space on GitHub Actions runner'

runs:
  using: 'composite'
  steps:
    - name: Free up disk space (Host SSD)
      shell: bash
      run: |
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /opt/hostedtoolcache \
          /usr/local/share/powershell \
          /usr/local/share/chromium \
          /usr/local/share/boost \
          /usr/local/julia* \
          /usr/local/aws* \
          /usr/share/swift \
          /usr/share/az_* \
          /usr/share/sbt \
          /var/lib/mongodb \
          /opt/az \
          /opt/google/chrome \
          /opt/microsoft \
          /usr/lib/google-cloud-sdk \
          /usr/local/gcloud
        sudo swapoff -a || true
        sudo rm -f /mnt/swapfile /swapfile || true
        sudo docker system prune --all --volumes --force
