from __future__ import annotations

from common.prompts import (
    GEMINI_TRANSCRIBE_SYSTEM_PROMPT,
    GEMINI_TRANSCRIBE_USER_PROMPT,
)

PIPELINE_SYSTEM_PROMPT = GEMINI_TRANSCRIBE_SYSTEM_PROMPT
PIPELINE_USER_PROMPT = GEMINI_TRANSCRIBE_USER_PROMPT
