openapi: 3.0.0
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    Transcript:
      properties:
        feedId:
          type: string
        transmissionId:
          type: string
        transcript:
          type: string
        startTimestamp:
          type: string
        endTimestamp:
          type: string
        missingPriorContext:
          type: boolean
        missingPostContext:
          type: boolean
        sourceAudioUris:
          items:
            type: string
          type: array
        canonicalAudioUri:
          type: string
        startAudioOffset:
          type: string
        endAudioOffset:
          type: string
        evaluationDecisions:
          items:
            type: string
          type: array
      required:
        - feedId
        - transmissionId
        - transcript
        - startTimestamp
        - endTimestamp
        - missingPriorContext
        - missingPostContext
        - sourceAudioUris
        - canonicalAudioUri
        - startAudioOffset
        - endAudioOffset
        - evaluationDecisions
      type: object
      additionalProperties: false
    ListTranscriptsResponse:
      properties:
        transcripts:
          items:
            $ref: "#/components/schemas/Transcript"
          type: array
        nextToken:
          type: string
      required:
        - transcripts
      type: object
      additionalProperties: false
    ListTranscriptsQueryParams:
      properties:
        limit:
          type: integer
          format: int32
          default: 100
        nextToken:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        order:
          type: string
          enum:
            - asc
            - desc
      type: object
      additionalProperties: false
    ScopeLevel:
      type: string
      enum:
        - FEED_SPECIFIC
        - GLOBAL
    Scope:
      properties:
        level:
          $ref: "#/components/schemas/ScopeLevel"
        targetFeeds:
          items:
            type: string
          type: array
      required:
        - level
        - targetFeeds
      type: object
      additionalProperties: false
    LogicalOperator:
      type: string
      enum:
        - ANY
        - ALL
    KeywordConditions:
      properties:
        evaluationType:
          type: string
          enum:
            - KEYWORD_MATCH
          nullable: false
        operator:
          $ref: "#/components/schemas/LogicalOperator"
        keywords:
          items:
            type: string
          type: array
        caseSensitive:
          type: boolean
      required:
        - evaluationType
        - operator
        - keywords
        - caseSensitive
      type: object
      additionalProperties: false
    RegexConditions:
      properties:
        evaluationType:
          type: string
          enum:
            - REGEX_MATCH
          nullable: false
        expression:
          type: string
        flags:
          type: string
      required:
        - evaluationType
        - expression
        - flags
      type: object
      additionalProperties: false
    GroupConditions:
      properties:
        evaluationType:
          type: string
          enum:
            - RULE_GROUP
          nullable: false
        operator:
          $ref: "#/components/schemas/LogicalOperator"
        childRuleIds:
          items:
            type: string
          type: array
      required:
        - evaluationType
        - operator
        - childRuleIds
      type: object
      additionalProperties: false
    RuleConditions:
      anyOf:
        - $ref: "#/components/schemas/KeywordConditions"
        - $ref: "#/components/schemas/RegexConditions"
        - $ref: "#/components/schemas/GroupConditions"
    RuleMetadata:
      properties:
        createdBy:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      required:
        - createdAt
        - updatedAt
      type: object
      additionalProperties: false
    Rule:
      properties:
        ruleId:
          type: string
        ruleName:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        scope:
          $ref: "#/components/schemas/Scope"
        conditions:
          $ref: "#/components/schemas/RuleConditions"
        metadata:
          $ref: "#/components/schemas/RuleMetadata"
      required:
        - ruleId
        - ruleName
        - isActive
        - scope
        - conditions
        - metadata
      type: object
      additionalProperties: false
    ListRulesQueryParams:
      properties:
        ruleIds:
          items:
            type: string
          type: array
          description: Optional list of rule IDs to filter by.
      type: object
      additionalProperties: false
    RuleCreate:
      properties:
        ruleName:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        scope:
          $ref: "#/components/schemas/Scope"
        conditions:
          $ref: "#/components/schemas/RuleConditions"
      required:
        - ruleName
        - scope
        - conditions
      type: object
      additionalProperties: false
    RuleUpdate:
      properties:
        ruleName:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        scope:
          $ref: "#/components/schemas/Scope"
        conditions:
          $ref: "#/components/schemas/RuleConditions"
      type: object
      additionalProperties: false
    SourceType:
      type: string
      enum:
        - bcfy_feeds
        - bcfy_calls
        - echo
        - openmhz
    Feed:
      properties:
        name:
          type: string
        sourceType:
          $ref: "#/components/schemas/SourceType"
        id:
          type: string
        sourceFeedId:
          type: string
        externalId:
          type: string
        sourceUrl:
          type: string
        archiveUrl:
          type: string
      required:
        - name
        - sourceType
        - id
      type: object
      additionalProperties: false
    FeedCreate:
      properties:
        name:
          type: string
        sourceType:
          $ref: "#/components/schemas/SourceType"
        sourceFeedId:
          type: string
        externalId:
          type: string
      required:
        - name
        - sourceType
        - sourceFeedId
        - externalId
      type: object
      additionalProperties: false
    OpenApiSpec:
      properties: {}
      type: object
      additionalProperties: {}
  securitySchemes:
    google_id_token:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
      x-google-auth:
        issuer: https://accounts.google.com
        jwksUri: https://www.googleapis.com/oauth2/v3/certs
        audiences:
          - ${google_auth_client_id}
info:
  title: radio-transcription-api
  version: 1.0.0
  contact: {}
paths:
  /api/v1/transcripts/{feedId}:
    get:
      operationId: ListTranscripts
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTranscriptsResponse"
        "401":
          description: Unauthorized
        "404":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                required:
                  - message
                type: object
      tags:
        - Transcripts
      security:
        - google_id_token: []
      parameters:
        - in: path
          name: feedId
          required: true
          schema:
            type: string
        - in: query
          name: limit
          required: false
          schema:
            default: 100
            format: int32
            type: integer
        - in: query
          name: nextToken
          required: false
          schema:
            type: string
        - in: query
          name: startTime
          required: false
          schema:
            type: string
        - in: query
          name: endTime
          required: false
          schema:
            type: string
        - in: query
          name: order
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
      x-google-backend: radio-transcription-api
  /api/v1/rules:
    get:
      operationId: ListRules
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Rule"
                type: array
        "401":
          description: Unauthorized
      tags:
        - Rules
      security:
        - google_id_token: []
      parameters:
        - description: Optional list of rule IDs to filter by.
          in: query
          name: ruleIds
          required: false
          schema:
            type: array
            items:
              type: string
      x-google-backend: radio-transcription-api
    post:
      operationId: CreateRule
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
        "401":
          description: Unauthorized
      tags:
        - Rules
      security:
        - google_id_token: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RuleCreate"
      x-google-backend: radio-transcription-api
  /api/v1/rules/{ruleId}:
    get:
      operationId: GetRule
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
        "401":
          description: Unauthorized
        "404":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                required:
                  - message
                type: object
      tags:
        - Rules
      security:
        - google_id_token: []
      parameters:
        - in: path
          name: ruleId
          required: true
          schema:
            type: string
      x-google-backend: radio-transcription-api
    put:
      operationId: UpdateRule
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
        "401":
          description: Unauthorized
        "404":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                required:
                  - message
                type: object
      tags:
        - Rules
      security:
        - google_id_token: []
      parameters:
        - in: path
          name: ruleId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RuleUpdate"
      x-google-backend: radio-transcription-api
    delete:
      operationId: DeleteRule
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "404":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                required:
                  - message
                type: object
      tags:
        - Rules
      security:
        - google_id_token: []
      parameters:
        - in: path
          name: ruleId
          required: true
          schema:
            type: string
      x-google-backend: radio-transcription-api
  /api/v1/feeds:
    get:
      operationId: ListFeeds
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Feed"
                type: array
        "401":
          description: Unauthorized
      tags:
        - Feeds
      security:
        - google_id_token: []
      parameters: []
      x-google-backend: radio-transcription-api
    post:
      operationId: CreateFeed
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feed"
        "401":
          description: Unauthorized
      tags:
        - Feeds
      security:
        - google_id_token: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedCreate"
      x-google-backend: radio-transcription-api
  /api/v1/feeds/{feedId}:
    get:
      operationId: GetFeed
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feed"
        "401":
          description: Unauthorized
        "404":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                required:
                  - message
                type: object
      tags:
        - Feeds
      security:
        - google_id_token: []
      parameters:
        - in: path
          name: feedId
          required: true
          schema:
            type: string
      x-google-backend: radio-transcription-api
    delete:
      operationId: DeleteFeed
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "404":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                required:
                  - message
                type: object
      tags:
        - Feeds
      security:
        - google_id_token: []
      parameters:
        - in: path
          name: feedId
          required: true
          schema:
            type: string
      x-google-backend: radio-transcription-api
  /api/v1/docs/openapi.json:
    get:
      operationId: GetSpec
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/OpenApiSpec"
                nullable: true
      tags:
        - Docs
      security:
        - google_id_token: []
      parameters: []
      x-google-backend: radio-transcription-api
servers:
  - url: https://${radio_transcription_api_service_name}/
    x-google-endpoint:
      allowCors: true
x-google-api-management:
  backends:
    radio-transcription-api:
      address: ${radio_transcription_api_url}
      path_translation: APPEND_PATH_TO_ADDRESS
      protocol: http/1.1
