[project]
name = "radio-transcription-common"
version = "0.1.0"
requires-python = ">=3.13, <3.14"

dependencies = [
    "fastapi>=0.110.0",
    "google-auth>=2.29.0",
    "google-cloud-storage>=2.18.2",
    "google-cloud-pubsub>=2.35.0",
    "google-cloud-logging>=3.14.0",
    "google-cloud-monitoring>=2.29.1",
    "gcloud-aio-storage>=9.6.4",
    "opentelemetry-api>=1.41.1",
    "opentelemetry-sdk>=1.41.1",
    "opentelemetry-exporter-gcp-trace>=1.12.0",
    "opentelemetry-exporter-gcp-monitoring>=1.6.0",
    "aiohttp>=3.14.1",
    "redis>=7.3.0",
    "pydantic>=2.10.6",
    "protobuf>=5.29.6",
]

[tool.setuptools]
packages = []
