name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Whether to start SSH session for debugging'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  component-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise, install tools
        uses: jdx/mise-action@v3

      - name: Generate protos
        run: mise run generate:protos

      - name: Run component tests
        run: mise run test:component

  e2e-tests:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise, install tools
        uses: jdx/mise-action@v3

      - name: Run E2E tests
        run: mise run test:e2e

      - name: Open SSH session if workflow fails
        uses: mxschmitt/action-tmate@v3
        if: github.event_name == 'workflow_dispatch' && inputs.debug_enabled
