name: Trigger Private Deployment

on:
  push:
    branches: [main]

jobs:
  signal-private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Bot Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DEPLOYMENT_BOT_APP_ID }}
          private-key: ${{ secrets.DEPLOYMENT_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Notify Private Repo
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "Triggering deployment..."
          gh workflow run dev_deploy.yml --repo ${{ secrets.DEPLOYMENT_REPO_TARGET }} --ref main -f app_deploy_sha=${{ github.sha }}