name: Trigger Private Deployment

on:
  push:
    branches: [main]

jobs:
  signal-private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Notify Private Repo
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
        run: |
          echo "Triggering deployment..."
          gh workflow run deploy.yml --repo ${{ secrets.PRIVATE_REPO_TARGET }} -f app_deploy_sha=${{ github.sha }} -f environment=dev -f deploy_release=true